# file: C:\Users\rober\AppData\Roaming\Python\Python313\site-packages\_pytest\_py\error.py
# hypothesis_version: 6.137.1

[267, 'P', 'R', 'UnknownErrnoNone', '[{}]: {}', '_', '__doc__', '__module__', 'errno', 'py.error', 'win32', '{}.{} {!r}: {} ']